#!/bin/bash
wget http://gpsmid.sourceforge.net/prebuild/Osm2GpsMid-CVS.jar -O /unsafe/krueger/Osm2GpsMid/Osm2GpsMid-CVS.jar

wget http://myapp.fr/cellsIdData/cells.txt.gz -O /unsafe/krueger/Osm2GpsMid/cells.txt.gz

wget http://download.geofabrik.de/osm/europe/austria.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/austria.osm.bz2
wget http://download.geofabrik.de/osm/europe/poland.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/poland.osm.bz2
wget http://download.geofabrik.de/osm/europe/albania.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/albania.osm.bz2
wget http://download.geofabrik.de/osm/europe/croatia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/croatia.osm.bz2
wget http://download.geofabrik.de/osm/europe/bosnia-herzegovina.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/bosnia.osm.bz2
wget http://download.geofabrik.de/osm/europe/bulgaria.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/bulgaria.osm.bz2
wget http://download.geofabrik.de/osm/europe/estonia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/estonia.osm.bz2
wget http://download.geofabrik.de/osm/europe/kosovo.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/kosovo.osm.bz2
wget http://download.geofabrik.de/osm/europe/lithuania.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/lithuania.osm.bz2
wget http://download.geofabrik.de/osm/europe/latvia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/latvia.osm.bz2
wget http://download.geofabrik.de/osm/europe/luxembourg.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/luxembourg.osm.bz2
wget http://download.geofabrik.de/osm/europe/macedonia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/macedonia.osm.bz2
wget http://download.geofabrik.de/osm/europe/moldova.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/moldova.osm.bz2
wget http://download.geofabrik.de/osm/europe/slovakia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/slovakia.osm.bz2
wget http://download.geofabrik.de/osm/europe/slovenia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/slovenia.osm.bz2
wget http://download.geofabrik.de/osm/europe/belgium.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/belgium.osm.bz2
wget http://download.geofabrik.de/osm/europe/belarus.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/belarus.osm.bz2
wget http://download.geofabrik.de/osm/europe/czech_republic.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/czech_republic.osm.bz2
wget http://download.geofabrik.de/osm/europe/france.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/france.osm.bz2
wget http://download.geofabrik.de/osm/europe/germany.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/germany.osm.bz2
wget http://download.geofabrik.de/osm/europe/great_britain.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/great_britain.osm.bz2
wget http://download.geofabrik.de/osm/europe/netherlands.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/netherlands.osm.bz2
wget http://download.geofabrik.de/osm/europe/norway.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/norway.osm.bz2
wget http://download.geofabrik.de/osm/europe/spain.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/spain.osm.bz2
wget http://download.geofabrik.de/osm/europe/switzerland.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/switzerland.osm.bz2
wget http://download.geofabrik.de/osm/europe/greece.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/greece.osm.bz2
wget http://download.geofabrik.de/osm/europe/denmark.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/denmark.osm.bz2
wget http://download.geofabrik.de/osm/europe/iceland.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/iceland.osm.bz2
wget http://download.geofabrik.de/osm/europe/italy.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/italy.osm.bz2
wget http://download.geofabrik.de/osm/europe/romania.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/romania.osm.bz2
wget http://download.geofabrik.de/osm/europe/cyprus.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/cyprus.osm.bz2
wget http://download.geofabrik.de/osm/europe/hungary.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/hungary.osm.bz2
wget http://download.geofabrik.de/osm/europe/ireland.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/ireland.osm.bz2
wget http://download.geofabrik.de/osm/europe/turkey.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/turkey.osm.bz2
wget http://download.geofabrik.de/osm/europe/ukraine.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/ukraine.osm.bz2
wget http://download.geofabrik.de/osm/europe/finland.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/finland.osm.bz2
wget http://download.geofabrik.de/osm/europe/sweden.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/sweden.osm.bz2
wget http://downloads.cloudmade.com/north_america/canada/ontario/ontario.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/ontario.osm.bz2
wget http://downloads.cloudmade.com/north_america/canada/british_columbia/british_columbia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/britishcolumbia.osm.bz2
wget http://downloads.cloudmade.com/asia/philippines/philippines.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/philippines.osm.bz2
wget http://downloads.cloudmade.com/asia/iran/iran.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/iran.osm.bz2
wget http://downloads.cloudmade.com/asia/sri_lanka/sri_lanka.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/sri_lanka.osm.bz2
wget http://downloads.cloudmade.com/asia/israel/israel.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/israel.osm.bz2
wget http://downloads.cloudmade.com/asia/india/india.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/india.osm.bz2
wget http://downloads.cloudmade.com/asia/saudi_arabia/saudi_arabia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/saudi_arabia.osm.bz2
wget http://downloads.cloudmade.com/asia/pakistan/pakistan.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/pakistan.osm.bz2
wget http://downloads.cloudmade.com/asia/south_korea/south_korea.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/south_korea.osm.bz2
wget http://downloads.cloudmade.com/asia/japan/japan.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/japan.bz2
wget http://downloads.cloudmade.com/africa/south_africa/south_africa.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/south_africa.osm.bz2
wget http://downloads.cloudmade.com/africa/zimbabwe/zimbabwe.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/zimbabwe.osm.bz2
wget http://downloads.cloudmade.com/africa/ethiopia/ethiopia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/ethiopia.osm.bz2
wget http://downloads.cloudmade.com/africa/nigeria/nigeria.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/nigeria.osm.bz2
wget http://downloads.cloudmade.com/africa/egypt/egypt.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/egypt.osm.bz2
wget http://downloads.cloudmade.com/africa/morocco/morocco.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/morocco.osm.bz2
wget http://downloads.cloudmade.com/africa/democratic_republic_of_the_congo/democratic_republic_of_the_congo.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/congo.osm.bz2
wget http://downloads.cloudmade.com/africa/kenya/kenya.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/kenya.osm.bz2
wget http://downloads.cloudmade.com/africa/seychelles/seychelles.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/seychelles.osm.bz2
wget http://downloads.cloudmade.com/africa/namibia/namibia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/namibia.osm.bz2
wget http://download.geofabrik.de/osm/europe/portugal.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/portugal.osm.bz2
wget http://downloads.cloudmade.com/africa/tunisia/tunisia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/tunesia.osm.bz2
wget http://downloads.cloudmade.com/south_america/brazil/brazil.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/brazil.osm.bz2
wget http://downloads.cloudmade.com/oceania/australia/australia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/australia.osm.bz2
wget http://downloads.cloudmade.com/oceania/new_zealand/new_zealand.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/new_zealand.osm.bz2
wget http://downloads.cloudmade.com/asia/russian_federation/russian_federation.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/russia.osm.bz2
wget http://downloads.cloudmade.com/asia/china/china.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/china.osm.bz2
wget http://downloads.cloudmade.com/asia/malaysia/malaysia.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/malaysia.osm.bz2
wget http://downloads.cloudmade.com/asia/thailand/thailand.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/thailand.osm.bz2
wget http://download.cloudmade.com/north_america/united_states/california/california.osm.bz2 -O /unsafe/krueger/Osm2GpsMid/california.osm.bz2