#!/bin/bash
#wget http://gpsmid.sourceforge.net/prebuild/Osm2GpsMid-CVS.jar -O /home/apmon/Osm2GpsMid/Osm2GpsMid-CVS.jar
wget http://gpsmid.sourceforge.net/prebuild/Osm2GpsMid-0.7.1-map65.jar -O /home/apmon/Osm2GpsMid/Osm2GpsMid-CVS.jar


wget http://myapp.fr/cellsIdData/cells.txt.gz -O /home/apmon/Osm2GpsMid/cells.txt.gz

wget http://download.geofabrik.de/osm/europe/malta.osm.pbf -O /home/apmon/planet_dumps/malta.osm.pbf
wget http://download.geofabrik.de/osm/europe/austria.osm.pbf -O /home/apmon/planet_dumps/austria.osm.pbf
wget http://download.geofabrik.de/osm/europe/poland.osm.pbf -O /home/apmon/planet_dumps/poland.osm.pbf
wget http://download.geofabrik.de/osm/europe/albania.osm.bz2 -O /home/apmon/planet_dumps/albania.osm.bz2
wget http://download.geofabrik.de/osm/europe/croatia.osm.bz2 -O /home/apmon/planet_dumps/croatia.osm.bz2
wget http://download.geofabrik.de/osm/europe/bosnia-herzegovina.osm.bz2 -O /home/apmon/planet_dumps/bosnia.osm.bz2
wget http://download.geofabrik.de/osm/europe/bulgaria.osm.bz2 -O /home/apmon/planet_dumps/bulgaria.osm.bz2
wget http://download.geofabrik.de/osm/europe/estonia.osm.bz2 -O /home/apmon/planet_dumps/estonia.osm.bz2
wget http://download.geofabrik.de/osm/europe/kosovo.osm.bz2 -O /home/apmon/planet_dumps/kosovo.osm.bz2
wget http://download.geofabrik.de/osm/europe/lithuania.osm.bz2 -O /home/apmon/planet_dumps/lithuania.osm.bz2
wget http://download.geofabrik.de/osm/europe/latvia.osm.bz2 -O /home/apmon/planet_dumps/latvia.osm.bz2
wget http://download.geofabrik.de/osm/europe/luxembourg.osm.bz2 -O /home/apmon/planet_dumps/luxembourg.osm.bz2
wget http://download.geofabrik.de/osm/europe/macedonia.osm.bz2 -O /home/apmon/planet_dumps/macedonia.osm.bz2
wget http://download.geofabrik.de/osm/europe/moldova.osm.bz2 -O /home/apmon/planet_dumps/moldova.osm.bz2
wget http://download.geofabrik.de/osm/europe/slovakia.osm.pbf -O /home/apmon/planet_dumps/slovakia.osm.pbf
wget http://download.geofabrik.de/osm/europe/slovenia.osm.bz2 -O /home/apmon/planet_dumps/slovenia.osm.bz2
wget http://download.geofabrik.de/osm/europe/belgium.osm.bz2 -O /home/apmon/planet_dumps/belgium.osm.bz2
wget http://download.geofabrik.de/osm/europe/belarus.osm.bz2 -O /home/apmon/planet_dumps/belarus.osm.bz2
wget http://download.geofabrik.de/osm/europe/czech_republic.osm.pbf -O /home/apmon/planet_dumps/czech_republic.osm.pbf
wget http://download.geofabrik.de/osm/europe/france.osm.pbf -O /home/apmon/planet_dumps/france.osm.pbf
wget http://download.geofabrik.de/osm/europe/germany.osm.pbf -O /home/apmon/planet_dumps/germany.osm.pbf
wget http://download.geofabrik.de/osm/europe/great_britain.osm.pbf -O /home/apmon/planet_dumps/great_britain.osm.pbf
wget http://download.geofabrik.de/osm/europe/netherlands.osm.pbf -O /home/apmon/planet_dumps/netherlands.osm.pbf
wget http://download.geofabrik.de/osm/europe/norway.osm.bz2 -O /home/apmon/planet_dumps/norway.osm.bz2
wget http://download.geofabrik.de/osm/europe/spain.osm.pbf -O /home/apmon/planet_dumps/spain.osm.pbf
wget http://download.geofabrik.de/osm/europe/switzerland.osm.pbf -O /home/apmon/planet_dumps/switzerland.osm.pbf
wget http://download.geofabrik.de/osm/europe/greece.osm.bz2 -O /home/apmon/planet_dumps/greece.osm.bz2
wget http://download.geofabrik.de/osm/europe/denmark.osm.bz2 -O /home/apmon/planet_dumps/denmark.osm.bz2
wget http://download.geofabrik.de/osm/europe/iceland.osm.bz2 -O /home/apmon/planet_dumps/iceland.osm.bz2
wget http://download.geofabrik.de/osm/europe/italy.osm.pbf -O /home/apmon/planet_dumps/italy.osm.pbf
wget http://download.geofabrik.de/osm/europe/romania.osm.pbf -O /home/apmon/planet_dumps/romania.osm.pbf
wget http://download.geofabrik.de/osm/europe/cyprus.osm.bz2 -O /home/apmon/planet_dumps/cyprus.osm.bz2
wget http://download.geofabrik.de/osm/europe/hungary.osm.bz2 -O /home/apmon/planet_dumps/hungary.osm.bz2
wget http://download.geofabrik.de/osm/europe/ireland.osm.bz2 -O /home/apmon/planet_dumps/ireland.osm.bz2
wget http://download.geofabrik.de/osm/europe/turkey.osm.bz2 -O /home/apmon/planet_dumps/turkey.osm.bz2
wget http://download.geofabrik.de/osm/europe/ukraine.osm.bz2 -O /home/apmon/planet_dumps/ukraine.osm.bz2
wget http://download.geofabrik.de/osm/europe/finland.osm.bz2 -O /home/apmon/planet_dumps/finland.osm.bz2
wget http://download.geofabrik.de/osm/europe/sweden.osm.pbf -O /home/apmon/planet_dumps/sweden.osm.pbf

wget http://download.geofabrik.de/osm/asia/china.osm.pbf -O /home/apmon/planet_dumps/china.osm.pbf
wget http://download.geofabrik.de/osm/asia/india.osm.pbf -O /home/apmon/planet_dumps/india.osm.pbf
wget http://download.geofabrik.de/osm/asia/israel_and_palestine.osm.pbf -O /home/apmon/planet_dumps/israel.osm.pbf
wget http://download.geofabrik.de/osm/asia/pakistan.osm.pbf -O /home/apmon/planet_dumps/pakistan.osm.pbf
wget http://download.geofabrik.de/osm/asia/philippines.osm.pbf -O /home/apmon/planet_dumps/philippines.osm.pbf
wget http://download.geofabrik.de/osm/asia/iraq.osm.pbf -O /home/apmon/planet_dumps/iraq.osm.pbf
wget http://download.geofabrik.de/osm/asia/kazakhstan.osm.pbf -O /home/apmon/planet_dumps/kazakhstan.osm.pbf
wget http://download.geofabrik.de/osm/africa/canary_islands.osm.pbf -O /home/apmon/planet_dumps/canary.osm.pbf
wget http://download.geofabrik.de/osm/africa/south_africa_and_lesotho.osm.pbf -O /home/apmon/planet_dumps/south_africa.osm.pbf
wget http://download.geofabrik.de/osm/central-america/haiti-and-domrep.osm.pbf -O /home/apmon/planet_dumps/haiti.osm.pbf
wget http://download.geofabrik.de/osm/south-america/brazil.osm.pbf -O /home/apmon/planet_dumps/brazil.osm.pbf
wget http://download.geofabrik.de/osm/south-america/colombia.osm.pbf -O /home/apmon/planet_dumps/colombia.osm.pbf
wget http://download.geofabrik.de/osm/south-america/argentina.osm.pbf -O /home/apmon/planet_dumps/argentina.osm.pbf

wget http://downloads.cloudmade.com/north_america/canada/ontario/ontario.osm.bz2 -O /home/apmon/planet_dumps/ontario.osm.bz2
wget http://downloads.cloudmade.com/north_america/canada/british_columbia/british_columbia.osm.bz2 -O /home/apmon/planet_dumps/britishcolumbia.osm.bz2
wget http://download.cloudmade.com/north_america/jamaica/jamaica.osm.bz2 -O /home/apmon/planet_dumps/jamaica.osm.bz2
wget http://downloads.cloudmade.com/asia/iran/iran.osm.bz2 -O /home/apmon/planet_dumps/iran.osm.bz2
wget http://downloads.cloudmade.com/asia/sri_lanka/sri_lanka.osm.bz2 -O /home/apmon/planet_dumps/sri_lanka.osm.bz2
wget http://downloads.cloudmade.com/asia/saudi_arabia/saudi_arabia.osm.bz2 -O /home/apmon/planet_dumps/saudi_arabia.osm.bz2
wget http://downloads.cloudmade.com/asia/south_korea/south_korea.osm.bz2 -O /home/apmon/planet_dumps/south_korea.osm.bz2
wget http://downloads.cloudmade.com/asia/japan/japan.osm.bz2 -O /home/apmon/planet_dumps/japan.osm.bz2
wget http://downloads.cloudmade.com/africa/zimbabwe/zimbabwe.osm.bz2 -O /home/apmon/planet_dumps/zimbabwe.osm.bz2
wget http://downloads.cloudmade.com/africa/ethiopia/ethiopia.osm.bz2 -O /home/apmon/planet_dumps/ethiopia.osm.bz2
wget http://downloads.cloudmade.com/africa/nigeria/nigeria.osm.bz2 -O /home/apmon/planet_dumps/nigeria.osm.bz2
wget http://downloads.cloudmade.com/africa/egypt/egypt.osm.bz2 -O /home/apmon/planet_dumps/egypt.osm.bz2
wget http://downloads.cloudmade.com/africa/morocco/morocco.osm.bz2 -O /home/apmon/planet_dumps/morocco.osm.bz2
wget http://downloads.cloudmade.com/africa/democratic_republic_of_the_congo/democratic_republic_of_the_congo.osm.bz2 -O /home/apmon/planet_dumps/congo.osm.bz2
wget http://downloads.cloudmade.com/africa/kenya/kenya.osm.bz2 -O /home/apmon/planet_dumps/kenya.osm.bz2
wget http://downloads.cloudmade.com/africa/seychelles/seychelles.osm.bz2 -O /home/apmon/planet_dumps/seychelles.osm.bz2
wget http://downloads.cloudmade.com/africa/namibia/namibia.osm.bz2 -O /home/apmon/planet_dumps/namibia.osm.bz2
wget http://download.geofabrik.de/osm/europe/portugal.osm.bz2 -O /home/apmon/planet_dumps/portugal.osm.bz2
wget http://downloads.cloudmade.com/africa/tunisia/tunisia.osm.bz2 -O /home/apmon/planet_dumps/tunesia.osm.bz2
wget http://downloads.cloudmade.com/oceania/australia/australia.osm.bz2 -O /home/apmon/planet_dumps/australia.osm.bz2
wget http://downloads.cloudmade.com/oceania/new_zealand/new_zealand.osm.bz2 -O /home/apmon/planet_dumps/new_zealand.osm.bz2
wget http://downloads.cloudmade.com/asia/russian_federation/russian_federation.osm.bz2 -O /home/apmon/planet_dumps/russia.osm.bz2
wget http://downloads.cloudmade.com/asia/china/china.osm.bz2 -O /home/apmon/planet_dumps/china.osm.bz2
wget http://downloads.cloudmade.com/asia/malaysia/malaysia.osm.bz2 -O /home/apmon/planet_dumps/malaysia.osm.bz2
wget http://downloads.cloudmade.com/asia/thailand/thailand.osm.bz2 -O /home/apmon/planet_dumps/thailand.osm.bz2
wget http://download.cloudmade.com/asia/afghanistan/afghanistan.osm.bz2 -O /home/apmon/planet_dumps/afghanistan.osm.bz2
wget http://download.cloudmade.com/asia/bangladesh/bangladesh.osm.bz2 -O /home/apmon/planet_dumps/bangladesh.osm.bz2
wget http://download.cloudmade.com/north_america/united_states/california/california.osm.bz2 -O /home/apmon/planet_dumps/california.osm.bz2
wget http://downloads.cloudmade.com/north_america/puerto_rico/puerto_rico.osm.bz2 -O /home/apmon/planet_dumps/puerto_rico.osm.bz2
wget http://downloads.cloudmade.com/north_america/united_states/louisiana/louisiana.osm.bz2 -O /home/apmon/planet_dumps/louisiana.osm.bz2
wget http://download.cloudmade.com/north_america/united_states/colorado/colorado.osm.bz2 -O /home/apmon/planet_dumps/colorado.osm.bz2
wget http://download.cloudmade.com/north_america/united_states/new_york/new_york.osm.bz2 -O /home/apmon/planet_dumps/new_york.osm.bz2
wget http://download.cloudmade.com/asia/indonesia/indonesia.osm.bz2 -O /home/apmon/planet_dumps/indonesia.osm.bz2
wget http://download.cloudmade.com/north_america/trinidad_and_tobago/trinidad_and_tobago.osm.bz2 -O /home/apmon/planet_dumps/trinidad.osm.bz2

wget http://download.cloudmade.com/north_america/mexico/mexico.osm.bz2 -O /home/apmon/planet_dumps/mexico.osm.bz2
wget http://download.cloudmade.com/south_america/venezuela/venezuela.osm.bz2 -O /home/apmon/planet_dumps/venezuela.osm.bz2
wget http://download.cloudmade.com/asia/lebanon/lebanon.osm.bz2 -O /home/apmon/planet_dumps/lebanon.osm.bz2
wget http://download.cloudmade.com/asia/singapore/singapore.osm.bz2 -O /home/apmon/planet_dumps/singapore.osm.bz2
wget http://download.cloudmade.com/asia/jordan/jordan.osm.bz2 -O /home/apmon/planet_dumps/jordan.osm.bz2
wget http://download.cloudmade.com/asia/syria/syria.osm.bz2 -O /home/apmon/planet_dumps/syria.osm.bz2
wget http://download.cloudmade.com/asia/bahrain/bahrain.osm.bz2 -O /home/apmon/planet_dumps/bahrain.osm.bz2
wget http://download.cloudmade.com/asia/brunei/brunei.osm.bz2 -O /home/apmon/planet_dumps/brunei.osm.bz2
wget http://download.cloudmade.com/asia/united_arab_emirates/united_arab_emirates.osm.bz2  -O /home/apmon/planet_dumps/uae.osm.bz2