	<!--
		Damages describe tags that will modify ways / areas with
		the colors way_damaged_border, way_damaged_decoration or area_damaged_border	
		this is taken from http://wiki.openstreetmap.org/wiki/WikiProject_Haiti
	-->
	<damages>
		<damage damageKey="earthquake:damage" damageValues="collapsed_buiding|damaged_infrastructure|landslide" />
		<damage damageKey="*" damageValues="collapsed" />
		<damage damageKey="impassable" damageValues="yes" />
	</damages>