  <colors>
	<!-- Map Screen -->
	<color of="map_background" is="009BFF9B" isAtNight="00002200"/>
	<color of="map_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="map_touched_button_background" is="00FFFF77"/>
	<color of="speed_background" is="009BFF9B"/>
	<color of="speed_text" is="00000000"/>
	<color of="titleBar_background" is="00FFFFFF" isAtNight="00222222"/>
	<color of="titleBar_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="solution_background" is="00FFFFFF" isAtNight="00777777"/>
	<color of="solution_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="altitude_background" is="00FFFFFF" isAtNight="00777777"/>
	<color of="altitude_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="wayName_background" is="00FFFFFF" isAtNight="00222222"/>
	<color of="wayName_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="area_label_text" is="00000000" isAtNight="00FFFFFF"/>	
	<color of="way_label_text" is="00000000" isAtNight="00FFFFFF"/>	
	<color of="way_label_text_abbreviated" is="00646464" isAtNight="00FFFFFF"/>	
	<color of="poi_label_text" is="00000000" isAtNight="00FFFFFF"/>	
	<color of="wayPoint_label_text" is="00000000" isAtNight="00FFFFFF"/>	
	<color of="oneway_arrow" is="00323232" isAtNight="00323232"/>	
	<color of="oneway_arrow_non_fitting" is="00505050" isAtNight="00505050"/>	
	<color of="recording_background" is="00FFFFFF" isAtNight="00777777"/>
	<color of="recording_suspended_text" is="000000FF" isAtNight="00FF0000"/>
	<color of="recording_on_text" is="00FF0000"/>
	<color of="cellid_log_on_text" is="00FFFF96"/>
	<color of="cellid_log_on_attempting_text" is="00FF5656" isAtNight="00FF0000"/>
	<color of="audioRec_text" is="00FF0000" isAtNight="00FF0000"/>
	<color of="dest_text" is="00000000" isAtNight="00FF0000"/>
	<color of="dest_line" is="00FF3232"/>
	<color of="map_cursor" is="00000000" isAtNight="00FFFFFF"/>
	<color of="map_posindicator" is="00000000" isAtNight="00FFFFFF"/>
	<color of="scalebar" is="00000000" isAtNight="00FFFFFF"/>
	<color of="zoom_button" is="00000000" isAtNight="00FFFFFF"/>
	<color of="zoom_text" is="00000000" isAtNight="00FFFFFF" />
	<color of="compass_direction_background" is="00FFFFC0" isAtNight="00000000"/>
	<color of="compass_direction_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="speeding_sign_border" is="00FF0000"/>
	<color of="speeding_sign_inner" is="00FFFFFF"/>
	<color of="speeding_sign_text" is="00000000"/>
	<color of="clock_background" is="009BFF9B"/>
	<color of="clock_text" is="00000000"/>
	<!-- Routing -->
	<color of="ri_at_dest" is="00C4C435"/>	
	<color of="ri_on_route" is="00B7FBBA"/>	
	<color of="ri_off_route_slight" is="00FFCD9B"/>	
	<color of="ri_off_route_full" is="00FF5402"/>	
	<color of="ri_not_at_route_line_yet" is="00808080"/>
	<color of="ri_check_direction" is="00FFFF64"/>
	<color of="ri_text" is="00000000"/>
	<color of="ri_distance_background" is="00C4C435"/>
	<color of="ri_distance_text" is="00000000"/>
	<color of="ri_eta_background" is="00C4C435"/>
	<color of="ri_eta_text" is="00000000"/>
	<color of="ri_off_distance_text" is="00000000"/>
	<color of="routeLine" is="0000C0C0"/>
	<color of="routeLine_border" is="0064FFFF"/>
	<color of="priorRouteLine" is="00006633"/>
	<color of="priorRouteLine_border" is="0033BFBF"/>
	<color of="routeDot" is="00FFFF00"/>
	<color of="routeDot_border" is="00FF0000"/>
	<!-- Icon Menu -->
	<color of="iconMenu_background" is="00000000"/>	
	<color of="iconMenu_tabButton_border" is="00707070"/>	
	<color of="iconMenu_tabButton_text" is="00FFFFFF"/>	
	<color of="iconMenu_tabButton_text_highlight" is="00FFFF00"/>	
	<color of="iconMenu_tabButton_text_inactive" is="00808080"/>	
	<color of="iconMenu_icon_text" is="00FFFFFF"/>	
	<color of="iconMenu_icon_border_highlight" is="00FFFF00"/>
	<color of="iconMenu_touched_button_background" is="00AAAA77"/>
	<!-- alert -->
	<color of="alert_background" is="00DEDEDE"/>	
	<color of="alert_border" is="00000000"/>	
	<color of="alert_title_background" is="00FFFFFF"/>	
	<color of="alert_text" is="00000000"/>	
	<!-- other screens -->
	<color of="tacho_background" is="00FFFFFF"/>	
	<color of="tacho_text" is="00000000"/>	
	<!-- way / area decorations -->
	<color of="bridge_decoration" is="00FFFFFF"/>	
	<color of="tunnel_decoration" is="00000000"/>	
	<color of="tollroad_decoration" is="00FFDDBB"/>	
	<color of="way_damaged_border" is="00FF0000"/>	
	<color of="way_damaged_decoration" is="00FF0000"/>	
	<color of="area_damaged_border" is="00FF0000"/>	
	<color of="search_background" is="00FFFFFF" isAtNight="00000000"/>
	<color of="search_arrows" is="00000000" isAtNight="00FFFFFF"/>
	<!-- FIXME these colors need tuning for night mode -->
	<color of="search_selected_typed" is="00FF0000" isAtNight="00FF8484"/>
	<color of="search_selected_rest" is="00FF6464" isAtNight="00FFFFFF"/>
	<color of="search_nonselected_typed" is="00000000" isAtNight="00BB6464"/>
	<color of="search_nonselected_rest" is="009696FA" isAtNight="00BBBBBB"/>
	<color of="search_touched_button_background" is="00FFFF77"/>
	<color of="search_button_text" is="00000000" isAtNight="00FFFFFF"/>
	<color of="search_button_border" is="00000000" isAtNight="009999BB"/>
	<!-- These colors are not used as of 2011-01-05, plan is to use with menus -->
	<color of="menu_background" is="00FFFFFF" isAtNight="00000000"/>
	<color of="menu_text" is="00000000" isAtNight="00FFFFFF"/>
  </colors>
