	<maxSpeedTemplates>
		<maxSpeedTemplate name="AT:urban" maxspeed="50" />
		<maxSpeedTemplate name="AT:land" maxspeed="100" />
		<maxSpeedTemplate name="DE:urban" maxspeed="50" />
	    <maxSpeedTemplate name="DE:city" maxspeed="50" />
	    <maxSpeedTemplate name="DE:zone30" maxspeed="30" />
     	<maxSpeedTemplate name="DE:living_street" maxspeed="7" />
		<maxSpeedTemplate name="DE:rural" maxspeed="100" />
     	<maxSpeedTemplate name="DE:motorway" maxspeed="250" />
		<maxSpeedTemplate name="FI:urban" maxspeed="50" />
		<maxSpeedTemplate name="nsl" maxspeed="97" />
		<maxSpeedTemplate name="national" maxspeed="97" />
		<maxSpeedTemplate name="Ortsgebiet" maxspeed="50" />
    	<maxSpeedTemplate name="city_limits" maxspeed="50" />
		<maxSpeedTemplate name="walk" maxspeed="7" />
	    <maxSpeedTemplate name="unknown" maxspeed="-1" />
	</maxSpeedTemplates>
